services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  mariadb:
    image: 'mariadb:latest'
    environment:
      MARIADB_DATABASE: dobitnik
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_USER: vlada
    ports:
      - '3306:3306'
