###
### POST request to EuWin server
POST http://127.0.0.1:8088/system
Content-Type: application/json

{
     "mainNumbersCombination": [
         8,
         19,
         1,
         29,
         4,
         39,
         41
     ],
     "bonusNumbers": [
         2,ø
         6,
         11
     ],
     "mainGamePool": 50,
     "mainGameSize": 3,
     "mainSystemSize": 6,
     "bonusPool": 12,
     "bonusSize": 3,
     "bonusSystemSize": 2
 }

###
