###
### POST request to EuWin server
POST http://127.0.0.1:8088/system
Content-Type: application/json

{
  "mainNumbersCombination": [
    5,
    12,
    14,
    24,
    31,
    35,
    41,
    52,
    53,
    56
  ],
  "mainGamePool": 59,
  "mainGameSize": 4,
  "mainSystemSize": 5,
  "bonusSystemSize": 2
}

###
